
DGDNN:
  model_name: DGDNN
  layers: 6
  num_nodes: 1026 # Fill dynamically in code if needed
  expansion_step: 7
  num_heads: 2
  active_layers: [true, false, false, false, false, false]
  timestamp: 19
  classes: 1
  diffusion_size: [95, 64, 128, 256, 256, 256, 128]
  embedding_size: [128, 384, 512, 512, 512, 384]
