# -----------------------------------------------------------------
# Configuration for the NASDAQ market (for the NEW DGDNN model)
# -----------------------------------------------------------------

# Parameters related to data loading and time periods
dataset_params:
  market: 'NASDAQ'
  train_sedate: ['2016-05-01', '2017-06-30']
  val_sedate: ['2017-07-01', '2017-12-31']
  test_sedate: ['2018-01-01', '2019-12-31']
  window_size: 19  # From paper: τ = 19
  use_fast_approximation: false

# -----------------------------------------------------------------

model_params:
  layers: 8          # From paper: L = 8
  expansion_step: 9  # From paper: K = 9
  num_heads: 3      # From paper should be 3
  active_layers: [true, true, true, true, true, true, true, true]

  # --- New simplified attention parameters ---
  # The output size for ALL attention layers. From paper's "embedding dimension".
  embedding_output_size: 128
  # The size of the internal MLP inside the attention block. 256 is a sensible default.
  embedding_hidden_size: 256
  # The size the raw features are projected to. Must be divisible by num_heads (3). 96 is a good choice.
  raw_feature_size: 96

  diffusion_size: [95, 128, 256, 512, 256, 128, 128, 128, 128]

  # Length must be layers = 8. Values are calculated input dimensions for each attention layer.
  embedding_size:
    - 224  
    - 384  # 384 / 3 = 128
    - 640  # 639 / 3 = 213
    - 384  # 384 / 3 = 128
    - 256  # 255 / 3 = 85
    - 256
    - 256
    - 256

# -----------------------------------------------------------------

# Parameters for the training process
training_params:
  learning_rate: 0.0002      # From paper: 2e-4
  weight_decay: 0.000015     # From paper: 1.5e-5
  epochs: 1200               # From paper
  neighbour_radius_coeff: 2.9e-3  # From paper: α = 2.9e-3